# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-21 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11, unique=True, verbose_name='客户卡号')),
                ('pwd', models.CharField(max_length=32, verbose_name='客户密码')),
                ('start_time', models.DateField(auto_now_add=True, verbose_name='开卡日期')),
                ('end_time', models.DateField(default=datetime.datetime(2019, 4, 22, 1, 19, 1, 167423), verbose_name='截止日期')),
                ('pay', models.IntegerField(verbose_name='充值')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='游戏名称')),
                ('user', models.ManyToManyField(to='web.CardInfo', verbose_name='客户游戏')),
            ],
        ),
    ]
