# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-22 03:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 11, 37, 58, 217254), verbose_name='截止日期'),
        ),
    ]
