# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-22 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190322_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_time', models.DateTimeField(auto_now_add=True, verbose_name='消费时间')),
                ('games', models.ManyToManyField(to='web.Game', verbose_name='消费游戏名称')),
            ],
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 15, 1, 22, 862158), verbose_name='截止日期'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.CardInfo', verbose_name='消费用户'),
        ),
    ]
