# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-22 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190322_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.IntegerField(choices=[(1, '次数'), (2, '时长')], default='1', verbose_name='游戏消费类型'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 15, 40, 27, 924836), verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='游戏名称'),
        ),
    ]
