# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-22 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190322_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 16, 52, 25, 373061), verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='游戏次数'),
        ),
        migrations.AlterField(
            model_name='game',
            name='number_of_times',
            field=models.IntegerField(blank=True, null=True, verbose_name='游戏次数'),
        ),
    ]
