# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-22 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190322_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='game',
            name='number_of_times',
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.CharField(default=2, max_length=10, verbose_name='时长或次数'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 17, 40, 23, 933791), verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(max_length=32, verbose_name='游戏消费类型'),
        ),
    ]
