# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-25 08:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190322_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='vip')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 16, 17, 21, 533994), verbose_name='截止日期'),
        ),
        migrations.AddField(
            model_name='game',
            name='vip',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web.Vip', verbose_name='客户游戏'),
            preserve_default=False,
        ),
    ]
