# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-25 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190325_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='vip',
            field=models.ManyToManyField(to='web.Vip'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 9, 8, 643847), verbose_name='截止日期'),
        ),
    ]
