# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-27 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190325_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.IntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='vip',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='vip',
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 27, 15, 50, 49, 12355), verbose_name='截止日期'),
        ),
        migrations.DeleteModel(
            name='Vip',
        ),
        migrations.AddField(
            model_name='time',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Game'),
        ),
        migrations.AddField(
            model_name='time',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CardInfo'),
        ),
    ]
