# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-27 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190327_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 27, 22, 59, 23, 563918), verbose_name='截止日期'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='games',
        ),
        migrations.AddField(
            model_name='payment',
            name='games',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web.Game', verbose_name='消费游戏名称'),
            preserve_default=False,
        ),
    ]
