# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-27 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20190327_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 27, 23, 52, 29, 273797), verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='time',
            name='title',
            field=models.CharField(default='dk', max_length=32, verbose_name='游戏简称'),
        ),
    ]
