# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-27 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20190327_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 27, 23, 54, 13, 681351), verbose_name='截止日期'),
        ),
    ]
