# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-28 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20190327_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='time',
            field=models.CharField(default=2, max_length=32, verbose_name='消费时长'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 21, 51, 56, 653109), verbose_name='截止日期'),
        ),
    ]
