# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-28 13:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20190328_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 21, 53, 2, 650777), verbose_name='截止日期'),
        ),
    ]
