# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-30 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20190328_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 21, 9, 37, 702527), verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CardInfo', verbose_name='消费用户'),
        ),
    ]
